artifact_uri: file:http://localhost:8000/1/01bebc27691a43399d7a98a1a6ed85b6/artifacts
end_time: 1593616814426
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 01bebc27691a43399d7a98a1a6ed85b6
run_uuid: 01bebc27691a43399d7a98a1a6ed85b6
source_name: ''
source_type: 4
source_version: ''
start_time: 1593616814416
status: 3
tags: []
user_id: Kubam
